jekyll/minima

- _layouts/default.html
Ported over from https://github.com/jekyll/jekyll/pull/4967 at the request of @parkr. :)
> default layout: html `lang` attribute should allow user customization

- minima.gemspec
fixes jekyll/jekyll#5145.
before:
> include _layouts, _includes, and _sass dir in gem

- _includes/footer.html
- example/_config.yml
I wrote this PR because I thought that having site.title shown twice in the footer was redundant, so I introduced the "author" variable in _config.yml to be shown just above the email address. Moreover, this behavior is optional, since if you don't define the "author" variable it falls back to the "title" variable.
> Added "author" in footer instead of double title

- minima.gemspec
This PR adopts the core template's gemspec file matcher, as fixed in https://github.com/jekyll/jekyll/pull/5152.
> Use upstream gemspec file matcher

- README.md
- _includes/disqus_comments.html
- _layouts/post.html
This PR enables the user to show, optionally, Disqus comments below each post.
In order to get this working the user only needs to add the following to `_config.yml`:
```yaml
disqus:
shortname: my_disqus_shortname
```
You can find out more about Disqus' shortnames [here](https://help.disqus.com/customer/portal/articles/466208).
The current behavior remains the same if no `disqus` property is supplied.
> Add support to Disqus

- example/_config.yml
- example/_posts/2016-05-20-welcome-to-jekyll.md
- example/about.md
- example/index.html
The Example site should closely resemble the default site generated by jekyll new to ease development
Included a markdown static-file, the _Welcome_ post and rewrote both index.html and _config.yml
> Update Example to resemble Default site

- _includes/head.html
- _includes/header.html
- example/Gemfile
- example/_config.yml
- example/index.html
This fixes #17. /cc @benbalter
This requires a change in the `jekyll new` template, sadly, namely in the listing of `site.posts`. We could potentially ship an `include` for `posts_list` or something so we don't have to update it in Jekyll in the future?
> Look for site.github.url if it exists

- .gitignore
- .travis.yml
- script/bootstrap
- script/build
- script/cibuild
To ensure the site builds. 
Fixes #32.
> Add Travis and a basic smoke test

- minima.gemspec
Fixes https://github.com/jekyll/minima/issues/29.
It's a quick fix to get the files added, but I'm hoping to fix this upstream and include it as a constant so that other themes can reference it.
> Fix gemspec regex

- _includes/header.html
- example/index.html
* When using github-pages gem and creating a site with the command `bundle exec jekyll new . -force`, there is inconstancies in the url links after build.
* even if site.url or site.baseurl are set, the site.github.url was used in the header.html snippet
* when running the site locally there are link to github.com instead of local jekyll server IP
* The patch is consistent with the previous commit: addf9a3787ef079fd26b8fd54d160f0cb684e57f
* The patch allows to generate only local links when using `bundle exec jekyll serve`
> priority to site.url when site.github.url is available

- _sass/minima.scss
- _sass/minima/_base.scss
- _sass/minima/_layout.scss
- _sass/minima/_syntax-highlighting.scss
Jekyll uses 2-spaces tab size for all its files (including the Sass in jekyll/jekyll `site/` directory), so they should be used here, too.
> Use standardized tab size of 2 spaces

- minima.gemspec
Update the regex in `minima.gemspec` to include `assets` directory in **Minima-2.0** gem.
Should've covered this in #43, my bad.. 
--
/cc @benbalter, @parkr
> Update gem regex to include new `assets` directory

- _includes/head.html
- _includes/header.html
- _layouts/home.html
replace existing liquid assignments `custom_url` and `full_base_url` with the new Jekyll filter `relative_url`
though **canonical URL** should always be an absolute URL (use `absolute_url` filter)
Ref: #56
> Use  new `absolute_url` and `relative_url` filters in minima

- minima.gemspec
replacing `development_dependency` with `runtime_dependency` to require ~> Jekyll 3.3
> Update gemspec to require at least Jekyll 3.3

- example/Gemfile
As we ship assets, I assume Jekyll 3.3 is required.
/cc @jekyll/minima
> Example should require Jekyll 3.3

- _includes/disqus_comments.html
> Use absolute_url filter for disqus

- _includes/header.html
- example/_config.yml
> add `header_pages` config to link only specific files in header

- minima.gemspec
Being shipped with Jekyll (checked on `3.3.0`).
> Remove incomplete status from spec summary

- README.md
- _layouts/home.html
- _layouts/post.html
- example/_config.yml
If it is not set, fall back to the previous default.
> Use date_format if set in configuration

- minima.gemspec
Now that 2.1.0 is out, I figured this wasn't appropriate anymore
> Remove 2.0 post-install message

- README.md
Add a section briefing on the various files within the theme-gem
Addresses #87
> Update README with theme content description

- _includes/header.html
This checks if there are any site.pages and only displays the nav tag if there are any.
> Fixes #115 - Only include the nav tag if there are pages to be displayed in the menu

- _sass/minima.scss
- assets/main.scss
This is an alternate approach to https://github.com/jekyll/minima/pull/86 which mirrors the approach we take on all the https://github.com/pages-themes themes.
The idea being, the default CSS file includes only an @import statement with the themes name, and all defaults and imports exist in the `_sass` directory.
That way a novice user can simply copy the `assets/style.scss` file (or write the one line themself) and add any custom css after the import statement.
The variable defaults already exist in `_sass/minima.scss` and are duplicative (and confusing/overly complex IMHO).
> More easily customizable CSS

- 404.html
Now that Minima is live on Github Pages and Jekyll itself will provide this template from `v3.5`, let's display the custom `404.html` instead of using the one provided by Github
> Add 404 page from jekyll `master`

- _layouts/home.html
it doesn't make a lot of sense to pull content from `layout: home` pages under the *Posts* heading. instead, this content should be included before the *Posts* section.
> handling content outside of posts

- README.md
- _includes/head.html
- minima.gemspec
From Jeyll 3.5, gem-based themes can declare plugin dependencies.
Let's improve SEO for all `minima` users.
fix #138 #96
> Add jekyll-seo-tag dependency

- _includes/footer.html
- _includes/header.html
- _includes/icon-github.html
- _includes/icon-twitter.html
- _layouts/post.html
This PR adds [Microformats](http://microformats.org/wiki/microformats2) markup to Minima's templates to make post content machine-readable and discoverable.
Microformats makes HTML content as easy to consume as JSON APIs without needing a separate feed. [Parser libraries](https://microformats.io) are available for Ruby, Python, PHP, Node and Go and more.
W3C recommended protocols, including [Webmention](https://www.w3.org/TR/webmention/) and [Micropub](https://www.w3.org/TR/micropub/) depend on Microformats and so it would be a great help for the default Jekyll theme's templates to support them.
- [Example Jekyll post with Microformats markup](https://barryf.github.io/jekyll/update/2017/09/21/welcome-to-jekyll.html)
- [JSON output from Microformats …
> Add Microformats markup

- minima.gemspec
Minima doesn't expose an executable
> Remove redundant entries in gemspec

- README.md
- _layouts/home.html
- _sass/minima/_layout.scss
Fixes #136 
Allow greater flexibility with the `home` layout
- Main heading can now be set via `index.md` with front matter key `title`
- This heading will now have the default size of `2em` from earlier `1.25em`
- `Posts` is now an `h2` heading and can be altered with fm-key `list_title`
- The entire Posts Listing and feed-link is now rendered only if the site has 1 or more `posts`
/cc @benbalter
> Increase flexibility of 'home' layout

- _config.yml
The `baseurl:` does't exists in the *_config* file.
> Update description comment in _config

- _posts/2016-05-19-super-short-article.md
- _sass/minima/_base.scss
- _sass/minima/_layout.scss
> Stick footer for short posts

- _sass/minima/_layout.scss
To solve the issue [#247](https://github.com/jekyll/minima/issues/247), flex properties of page-content in `_layout.scss` are changed.
**before**
**after**
> Footer overlapping issue (Support Microsoft Explorer 11)

- _config.yml
Change path to `about.md`, since `about.html` is confusing.
Fixes #253.
> Fix example header_pages in config

- _sass/minima/_layout.scss
The original code did not apply the proper `line-height` to the site title, offsetting it vertically from the center.
Before:
After:
> Fix site title line height

- _config.yml
I don't know if the existing comment reflected something I don't understand. Since the `twitter_username` field is no longer present at all, though, it felt like something that simply needed to be updated after the config file evolved.
> Update multiline config comment.

- _sass/minima/_layout.scss
Hi 👋, this is my first PR to the minima project.
For smaller view sizes, the footer leaves an empty column of space.
Like this:
Remove the columns for these smaller view sizes by wrapping `.one-half` in a media query using `$on-large`.
So it now looks like this:
The footer on larger view sizes is unchanged.
> Fix footer stacking issue for smaller view sizes

- .travis.yml
- Gemfile
- minima.gemspec
This adds Jekyll 4.0 support to **`2.5-stable`** branch by backporting #351 (and some additional minor changes to `.travis.yml`).
@DirtyF, @mattr-  IMO, a `minima-2.5.1` should be deployed a.s.a.p *before shipping Jekyll 4.0* so that
using `jekyll new` with Jekyll 4.0 allows using Minima 2.5 by default.
> Allow use and testing with Jekyll 4.x

- _sass/minima/_base.scss
I discovered the corners of code blocks look not correct currently.
That's because the `border-radius` of `.highlight` didn't set, so I fix it now.
> Set the border radius of highlight

- _includes/favicons.html
- _includes/head.html
Add a placeholder of favicons, so that users do not need to override the whole `head.html` to configure favicons, instead, just override `favicons.html`.
> Add a placeholder of favicons

- _sass/minima/initialize.scss
This fixes the issue where nested elements were rendered incorrectly (e.g. `<code>` nested under headings `<h1>`..`<h6>`) because of using `px` units.
Resolves #92 
Closes #304 
Closes #372
Closes #394
> Use "em" unit in relative-font-size mixin

- _sass/minima/_base.scss
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
closes #306
>  Add `overflow-wrap: break-word` to body tag

- History.markdown
- _sass/minima/_base.scss
- _sass/minima/initialize.scss
This fixes a miscalculation on my part in #435 
`$base-font-size * $ratio` actually translates to using `rem` units.
Using `em` units render sizes relative to the immediate parent element (which is *not* always desirable).
> Use "rem" unit in relative-font-size mixin

- _posts/2016-05-20-this-post-demonstrates-post-content-styles.md
- _sass/minima/_layout.scss
In order to prevent browsers from rendering them smaller than our `base_font_size` of 16px.
- `h5` and `h6` are a *larger* than `p` elements by couple of pixels each on all devices.
- `h5` takes on current small-screen size of `h4`
- `h4` size has been tweaked to remain at the same size on all devices.
Resolves #430 
Resolves #374 
/cc @hszhakka @alexhuangster
> Add font-size styles for elements h5 and h6

- _sass/minima/_base.scss
- _sass/minima/_layout.scss
The prefix is not needed in modern versions of webkit-based browsers:
https://caniuse.com/#feat=calc
> Stop prefixing CSS calc with `-webkit-`

- _includes/footer.html
- _sass/minima/_layout.scss
- Render a list-item (for `site.author` and `site.email`) in footer only when configured.
- Make `.social-links` a sibling of the `.footer-col-wrapper` (which now includes only `footer-col` by default). So that it is always a separate block independent of the presence of `.footer-col` divs.
- Single-line `site.description` no longer breaks the layout.
- On `$medium` viewport widths and above, use flexbox to align footer columns and social-links div. Stack vertically on smaller devices.
- Adjust social link margins so that they fold nicely on all viewport sizes when numerous icons are rendered.
Closes #446
> Re-implement site footer markup and styles

- _sass/minima/_layout.scss
Translating the title `"Some articles are just so long they deserve a really long title to see if things will break well"` into Turkish yields:
Note that some characters almost touch each other across lines on `master`
---
> Improve readability of post titles with diacritics

- _sass/minima/_base.scss
> Set margins of hr to improve readability

- _sass/minima/_base.scss
- _sass/minima/initialize.scss
> Export a variable to let users to custom the font family of code

- History.markdown
- _sass/minima/_layout.scss
This margin style is taken from [`minima-next`](https://github.com/jekyll/minima/pull/294). Since that branch seems will suspend for a long time, I make this PR by just adopting the headline margin style.
Before:
After:
> Adjust margins of headlines to make sections clear

- README.md
- _includes/custom-head.html
- _includes/head.html
Users may not only want to add favicons in the head but also add anything they want, so rename `favicons.html` to `custom-head.html` can indicate the purpose of the template file.
> Rename favicons.html to custom-head.html

- .travis.yml
- Installing via a shell script was messing with the build cache.
- Jekyll ~> 3.5 is the same as Jekyll ~> 3.8.0.
- Test with just one Ruby version since there isn't any actual Ruby code bundled with the gem (except for the gemspec) that warrants testing with multiple Ruby versions.
> [chore] Normalize Travis CI builds

- _sass/minima/_base.scss
Since `relative-font-size` uses `rem`, for avoiding the abnormal size cause by adjusting `base-font-size`, we need to set the font size of the root element to `base-font-size`.
> Specify the font size of the root element

- .travis.yml
> chore(deps): bump Ruby version

- .travis.yml
- Gemfile
So that CI can reliably run with Jekyll 3.8, 3.9 and 4.x
> Conditionally load GFM-parser gem in CI builds

- minima.gemspec
Primarily, this fixes the `spec.version` attribute which was not updated during the last release.
Secondarily, also removes some unnecessary whitespace.
> Fix theme gemspec

- _sass/minima/initialize.scss
This is what happens on Linux when Segoe UI Emoji is available, but Segoe UI isn't:
`system-ui` is provided by modern browsers as [a cross-platform default font](https://caniuse.com/font-family-system-ui). This is how it looks with `system-ui` in the font list:
It was a controversial choice back in 2017. because it did not address i18n well and therefore it was removed from Bootstrap twbs/bootstrap#22377. However, it was added back in v5 twbs/bootstrap#30561.
> Added system-ui as a cross-platform default font

- .github/workflows/ci.yaml
Follow-up to #608
- Trigger workflow for `pull_request` event as well.
- Improve job name in statuses.
- Set env once for all steps.
- Run `bundle install` as part of `setup-ruby` action.
> Improve CI workflow configuration

- README.md
This PR fixes a typo in the README for 3.0 in [this section](https://github.com/jekyll/minima#customizing-templates):
> In Minima 3.0, if you only need to customize the colors of the theme, refer to the subsequent section on skins. To have your *CSS overrides* in sync with upstream changes released in future versions, you can collect all your overrides for the Sass variables and mixins inside a sass file placed at `_sass/minima/custom-variables.scss` and all other overrides inside a sass file placed at path `_sass/minima/custom.scss`.
Currently, the path at the end `_sass/minima/custom.scss` won't overwrite any SCSS content. It should be `_sass/minima/custom-styles.scss` instead.
> Fix custom-styles.scss name in README

- README.md
Put the remainder of seeting the url field before setting the disqus shortname, so that people can see the message clearly.
Closes #626
> Improve the msg to enable disqus in README

- _sass/minima/initialize.scss
Resolves #653
Restore the emoji color in edge/chrome browsers in windows system. change base-font-family sequence, i.e. putting the "Segoe UI Emoji" before "Segoe UI Symbol"
> change base-font-family sequence

- _sass/minima/_base.scss
- _sass/minima/_layout.scss
```
Deprecation Warning: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
```
However, `math.div` is not supported by `sass` or `sassc` used in older version of jekyll-sass-converter. Therefore this PR fixes it in a backward compatible way by replaceing ` / 2` with ` * .5`, and replacing ` / 3` with ` * 33.3333333333 * .01` (a hack for precision in Sass). The css output is exactly same as before.
- Fixes #699
@ashmaroli
> Fix deprecation warnings from Dart Sass

- _config.yml
- Group theme-specific settings separately from *build settings*.
- Comment out settings since we no longer build the demo-site off the `master` branch. This helps those who forks the theme repository for use as Jekyll source directory.
> Improve readability of config file

- .github/workflows/demo_site.yml
Since automatic builds off `master` fails when triggered post a pull-request merge.
> Trigger demo-site build manually

- _config.yml
This update to _config.yml tries to avoid some confusion I ran into after choosing Minima as the theme for my GH Pages site. I did not want to build locally, but let GitHub do the job. Here are the changes I made:
- Since GH Pages still uses Minima 2.5.1, I added a block on how to use the latest Minima version anyway. 
- My header_pages did not show up in the specified order. It was an indentation error, for some reason I thought that it is a minima setting (minima.header_pages). I placed it before the minima block to avoid this confusion.
- The skin setting is missing in the current default _config.yml, I added it here.
> Improve documentation for config options

- _includes/disqus_comments.html
I create local modification, and only using absolute URL make Disqus works.
> Minimal fixes for Disqus

- _sass/minima/_layout.scss
I've cloned this repo on my machine, after running `bundle install`, I executed the `./script/server` command and I've got the _same_ deprecation message described by me in #796 . The only difference is I used the next patch version of ruby: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]` in my local minima repo.
The cause of the error seems to be the SASS compiler (I guess this version I have in my `Gemfile.lock`: `sass-embedded (1.77.8-x86_64-linux-gnu)`), because the deprecation message told me to read this page: https://sass-lang.com/documentation/breaking-changes/mixed-decls/ 
The deprecation message warns the offending line can impact the appearance of a page in the browser when the CSS nesting module will be introduced in the future …
> Fix deprecation warnings (#796)

- .github/workflows/release.yml
- minima.gemspec
- theme_version.rb
Build and release **minima-2.5.2** via GitHub Actions
> Release gem from 2.5-stable via GitHub Actions

- History.markdown
Move entries related to updates to `2.5-stable` branch to heading `## 2.5.2`
> Update History document for v2.5.2

- _sass/minima/_base.scss
After #677 , social icons slightly clips, probably due to issues similar to https://gsap.com/community/forums/topic/16844-svg-overflowing-its-bounding-box-while-scaling/
For example, see the right edge of the GitHub icon 
The CSS property added in this PR fixes it.
> Avoid clipping responsive social SVG icons

- _includes/google-analytics.html
Adapted from patch #824 for `2.5-stable` branch by @iTiamo
https://github.com/jekyll/minima/issues/816#issuecomment-2497302453 : 
> creating a file called `google-analytics` in my local directory `_includes` with the snippet that was provided to me...
> ```html
>
><script async src="https://www.googletagmanager.com/gtag/js?id={{ site.google_analytics }}"></script>
><script>
>  window.dataLayer = window.dataLayer || [];
>  function gtag(){dataLayer.push(arguments);}
>  gtag('js', new Date());
>
>  gtag('config', '{{ site.google_analytics }}');
></script>
>```
>
> This caused data to start flowing into my Google Analytics instance.
> Fix Google Analytics script

- _includes/footer.html
- _includes/head.html
- _includes/header.html
- _layouts/base.html
* Easier to read.
* Avoids being highlighted as an error in some text-editors.
> Use single-quotes when nested within double-quoted attributes

- README.md
- _config.yml
- _layouts/home.html
`show_excerpts` is not a configuration key defined by Jekyll. So move it to be under the `minima` namespace.
> Move `show_excerpts` setting to be under `minima` namespace

- _sass/minima/_base.scss
- max-width of **child elements** of `.wrapper` now equals `$content-width` &mdash; no more complicated math needed to determine width of *content text*.
- consistent padding at all viewport sizes.
> Simplify `.wrapper` style definition

- README.md
- _includes/sub-footer.html
- _layouts/base.html
Introduce new inclusion / include_file named `sub-footer.html` to allow inserting markup before the closing `</body>` tag.
- No need to customize `_layouts/base.html`.
- No need to customize `_includes/footer.html`.
> Simplify inserting markup before closing body tag

- README.md
- _config.yml
- _includes/header.html
- _includes/nav-items.html
- _sass/minima/_layout.scss
- Make the header fixed to the top of viewport to avoid scrolling to top especially when the current page is a very long post.
- Nav element on small-screens now span the full viewport height regardless of number of link-items.
- Introduce new include_file / inclusion named `nav-items.html` to render navigation link-items for all screen-sizes.
- Move `header_pages` config data into the `minima` namespace as **`minima:nav_pages`**
- Menu icon is now a Font Awesome icon instead of inline SVG.
> Improve navigation styling and experience

- _sass/minima/_base.scss
- Add an offset between glyph and underline
- Render underline with `$brand-color` instead of `$link-hover-color`.
> Improve link underline styling

- _sass/minima/_base.scss
- _sass/minima/_layout.scss
Make better use of limited view-space on small screens.
Was `15px !default` in v2.5.
Is currently `30px !default` on `master`.
Now it will be `18px !default`.
> Reduce wrapper padding on small screens

- _sass/minima/_base.scss
- _sass/minima/skins/auto.scss
- _sass/minima/skins/solarized.scss
To be able to visually distinguish paragraph-text and headings, especially `h4, h5, h6` that have similar font-sizes to `p` elements.
> Render headings and text in different colors

- _sass/minima/_base.scss
- _sass/minima/_layout.scss
But retain existing style for `.post-title`.
> Set default `font-weight` of headings to `500`

- _posts/2016-05-19-codeblocks-ahoy.md
- _sass/minima/_base.scss
- _sass/minima/skins/auto.scss
- _sass/minima/skins/solarized.scss
The rendering of code snippets with syntax-highlighting have not been adapted to suit various languages across available skins. This pull request reimplements the style rules around both inline-code snippets and code-snippet blocks.
> Refresh styling of highlighted code snippet blocks

- _includes/header.html
- _sass/minima/_layout.scss
Instead of having the icon for `#nav-trigger` remain *the triple-bars* / *hamburger* regardless of having the mobile navigation displayed, toggle between the triple-bars and ✖️ based on the state of the trigger.
> Toggle icons based on `#nav-trigger` state

- _sass/minima/skins/auto.scss
- _sass/minima/skins/solarized.scss
The behavior of `@extend` is slightly different between the legacy Sass engine and modern Sass engine.
> Re-establish compatibility with legacy Sass engine

- _posts/2016-05-20-this-post-demonstrates-post-content-styles.md
- _sass/minima/_layout.scss
- Override system-specific / browser-specific styling of `input type="checkbox"`
- Task-lists are rendered flush against `.wrapper` in contrast to (un-)ordered lists that have a left-margin.
- CSS is dependent on markup / class names rendered by kramdown extension `kramdown-parser-gfm`.
<br />
Resolves #881
> Adapt styles for GFM task-lists

- _includes/footer.html
- _includes/head.html
Move directive to load Font Awesome stylesheet from remote CDN to just before the `.site-footer` in order to improve page load speeds *slightly*.
Additionally, the `<link />` tags are given `id` attributes to allow easy access via custom JavaScript if needed.
> Delay loading font-awesome stylesheet from CDN
