_includes/head.html
Taking advantage of jekyll/jekyll#4917 to solve jekyll/jekyll#5066
=> Use normalize_whitespace filter for meta description

README.md
=> Document how to link to the theme styles

_includes/head.html
Fix for #34 
Look to site.url if set; otherwise site.github.url
=> Look to site.url when available

README.md
resquested by @benbalter in #36 
---
Fixes #36.
=> Move instruction for CSS in install section

example/index.html
=> Set index layout to default

example/index.html, example/index.md
replace `example/index.html` with `example/index.md` to mirror a site generated by jekyll 3.3.0
=> replace `example/index.html` with `example/index.md`

_sass/minima/_base.scss
This should do the trick. Please rewiew it. :rocket:
=> Close #55: Improve mobile user experience

script/build
Probably the most simplest of PRs lol, however, I couldn't ignore it. 😄
=> Corrected misspelled word

README.md
=> Update default local URL

_posts/2016-05-20-this-post-demonstrates-post-content-styles.md, _sass/minima.scss, _sass/minima/_base.scss
=> Add default table styles

README.md
This changes the documentation to match the version in _config.yml
in https://github.com/jekyll/minima/pull/141.
=> Update social_sites in README

History.markdown, minima.gemspec
=> Release 2.2.1

_sass/minima.scss
Add a system font stack to support different OSes for a more comfortable & pleasing look. This exact stack is used by https://github.com/ as well
=> Add better system fonts

_includes/header.html
Related: 76a8443f64226cf82959503ce867b63921cd9183
=> Add missing hyphen

README.md
So as to not confuse users with information regarding Minima 3.0
=> Add a disclaimer to the README

README.md
As `master`is protected, have to go through a PR to edit the README. 🤷‍♂️
=> Docs: disclaimer italics

_includes/footer.html
Removed hyphens on liquid tag (site.description)
=> Removed unnecessary whitespace-controls

_layouts/home.html
`site.minima.date_format` is a value independent of the loop context as the loop is iterating through `site.posts`. Also, since the value is static for a given build session the variable `date_format` is assigned the same value for every post in the site.
=> Assign static value to variable outside forloop

README.md
Documentation update regarding change made via https://github.com/jekyll/minima/commit/27d1d40db23032e4964c61bb32d0c21d8c12736c
=> Update README section on adding favicons to site

_layouts/post.html, _posts/2016-05-20-this-post-demonstrates-post-content-styles.md
Hello there!
With this PR, I'd like to add multiple author field on post layout.
=> Support mutiple authors on post layout

_layouts/home.html, _sass/minima/_layout.scss
Prior art: #150 
Resolves #159 
(total of 3 pages)
=> Support pagination through posts in home layout

_layouts/post.html
=> Show the last modified date of posts

README.md, _config.yml, _includes/footer.html, _includes/social.html, _layouts/home.html, _sass/minima/_layout.scss
=> Remove RSS icon from the social media list

README.md, _sass/minima-classic.scss, _sass/minima-solarized.scss, _sass/minima/initialize.scss, assets/css/style.scss
Change import paths in skins so that the partials are not so tightly coupled.
Also updates the README to add clarity on the theme contents and their overriding at source directory.
Resolves #474
=> Improve customizability of the theme

.github/workflows/ci.yaml
This will replace the travis CI configuration
=> Add a basic workflow file for building minima

_includes/google-analytics.html
closes #561
A window attribute was missing.
=> Fix script used for Google Analytics

README.md
Fixes typo mentioned in https://github.com/jekyll/minima/issues/645.
=> Make docs consistent with code

404.html
Update `404.html` to use `base.html` layout instead of `default.html` layout.
Fixes #712
=> Fix reference to base layout in `404.html`

_sass/minima/skins/auto.scss
To be the same color prior to change in cf7e884
=> Adjust table-text color based on heading-color

_sass/minima/skins/auto.scss, _sass/minima/skins/solarized.scss
Adjust contrast to resemble the subtlety of the *classic* skin.
=> Adjust table border contrast

_config.yml, _config_theme-dev.yml, script/build, script/server
To keep the `_config.yml` bare in order to avoid config leaks in downstream sites.
=> Move development config to a separate config file
